Add -fno-missing-braces to compiler flags to avoid compilation error
Works around the following compilation issue:

/home/dannf/git/edk2-debian/Shell/Library/DPath.c:1324:3: error: missing braces around initializer [-Werror=missing-braces]
   HARDWARE_DEVICE_PATH,
   ^
/home/dannf/git/edk2-debian/Shell/Library/DPath.c:1324:3: error: (near initialization for ‘DevPathTable[0]’) [-Werror=missing-braces]
cc1: all warnings being treated as errors