autopkgtest: Fix regression in test_aavmf_ms_secure_boot_unsigned
  ======================================================================
  ERROR: test_aavmf_ms_secure_boot_unsigned (__main__.BootToShellTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/autopkgtest.IxhnlS/build.72U/src/debian/tests/shell.py", line 174, in test_aavmf_ms_secure_boot_unsigned
      iso = GrubShellBootableIsoImage('AA64', use_signed=False)
  TypeError: GrubShellBootableIsoImage.__init__() got an unexpected keyword argument 'use_signed'

Fix by porting it to the new GrubShellBootableIsoImage interface.